name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Please adjust README when bumping version.
        rust: [stable, 1.59.0]
    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      uses: actions-rs/toolchain@v1.0.6
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        components: rustfmt, clippy
        override: true
    - name: Install deps
      run: sudo apt-get install -y clang-12 libelf-dev zlib1g-dev
    - name: Symlink clang
      run: sudo rm -f /bin/clang && sudo ln -s /usr/bin/clang-12 /bin/clang
    - name: Build
      run: cargo build --verbose --workspace --exclude runqslower
    - name: Build capable example with static libelf and libz
      run: RUSTFLAGS='-L /usr/lib/x86_64-linux-gnu' cargo b --package capable --features=static
    - name: Run tests
      # Skip BTF tests which require sudo
      # Skip BTF dump float test for now, we can enable it when we have access to clang 13+
      run: cargo test --verbose --workspace --exclude runqslower -- --skip test_object --skip test_btf_dump_float --skip test_tc
    - name: Run BTF tests
      run: cd libbpf-rs && cargo test --verbose -- test_object test_tc
    - name: Run rustfmt
      run: cargo fmt --package libbpf-cargo libbpf-rs -- --check
    - name: Run clippy
      run: cargo clippy --tests -- -D warnings
