[package]
name = "libbpf-cargo"
description = "Cargo plugin to build bpf programs"
repository = "https://github.com/libbpf/libbpf-rs"
homepage = "https://github.com/libbpf/libbpf-rs"
documentation = "https://docs.rs/crate/libbpf-cargo"
readme = "../README.md"
version = "0.13.1"
authors = ["Daniel Xu <dxu@dxuuu.xyz>"]
edition = "2021"
license = "LGPL-2.1 OR BSD-2-Clause"
keywords = ["bpf", "ebpf", "libbpf"]

[badges]
maintenance = { status = "actively-developed" }

# Crate is named libbpf-cargo to be consistent with libbpf-rs.
# Binary must be named cargo-${SUBCOMMAND} to interop with cargo.
[[bin]]
name = "cargo-libbpf"
path = "src/main.rs"

[lib]
path = "src/lib.rs"

[features]
# When turned on, link against system-installed libbpf instead of building
# and linking against vendored libbpf sources
novendor = ["libbpf-sys/novendor"]

[dependencies]
anyhow = "1.0"
cargo_metadata = "0.14"
libbpf-sys = { version = "1.0.3" }
memmap2 = "0.5"
num_enum = "0.5"
regex = "1.6.0"
scroll = "0.11"
scroll_derive = "0.11"
semver = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3.3"
thiserror = "1.0"
clap = { version = "3.1", default-features = false, features = ["std", "derive"] }

[dev-dependencies]
goblin = "0.4"
