apiVersion: v1
kind: ServiceAccount
metadata:
  name: ebpf-pod-resize-demo
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ebpf-pod-resize-demo
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: ebpf-pod-resize-demo
    namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ebpf-pod-resize-demo
  namespace: kube-system
  labels:
    k8s-app: ebpf-pod-resize-demo
spec:
  selector:
    matchLabels:
      name: ebpf-pod-resize-demo
  template:
    metadata:
      labels:
        name: ebpf-pod-resize-demo
    spec:
      serviceAccountName: ebpf-pod-resize-demo
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      hostNetwork: true
      hostPID: true
      hostIPC: true
      volumes:
      - name: sys-volume
        hostPath:
          path: /sys
      - name: usr-src-volume
        emptyDir: {}
      - name: usr-lib-modules-volume
        emptyDir: {}
      - name: var-run-containerd-volume
        hostPath:
          path: /var/run/containerd
      initContainers:
      - name: init-ebpf-pod-resize
        image: skiibum/ebpf-pod-resize:demo
        imagePullPolicy: IfNotPresent
        command: ["/init-ebpf-pod-resize.sh"]
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - name: usr-src-volume
          mountPath: /usr/src
          readOnly: false
        - name: usr-lib-modules-volume
          mountPath: /usr/lib/modules
          readOnly: false
      containers:
      - name: ebpf-pod-resize
        image: skiibum/ebpf-pod-resize:demo
        imagePullPolicy: IfNotPresent
        command: ["/launch-ebpf-pod-resize.sh"]
        resources:
          requests:
            cpu: 500m
            memory: 400Mi
        volumeMounts:
        - name: sys-volume
          mountPath: /sys
          readOnly: false
        - name: usr-src-volume
          mountPath: /usr/src
          readOnly: false
        - name: usr-lib-modules-volume
          mountPath: /usr/lib/modules
          readOnly: false
        - name: var-run-containerd-volume
          mountPath: /containerd
          readOnly: true
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add: ["SYS_ADMIN", "BPF", "PERFMON"]
