apiVersion: v1
kind: Pod
metadata:
  name: kube-build-pod
  annotations:
    "ebpf-resize": '{
            "cname": "kube-build-ctr",
            "commands": ["make"],
            "resize": "{\"requests\":{\"memory\":\"1Gi\"},\"limits\":{\"memory\":\"1Gi\"}}"
    }'
spec:
  containers:
  - name: kube-build-ctr
    image: skiibum/kube-build:v1.25
    imagePullPolicy: IfNotPresent
    command: ["tail", "-f", "/dev/null"]
    resources:
      limits:
        cpu: "2"
        memory: "50Mi"
      requests:
        cpu: "1"
        memory: "50Mi"
