apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: configmapgenerators.nullable.se
spec:
  group: nullable.se
  names:
    kind: ConfigMapGenerator
    plural: configmapgenerators
    shortNames:
    - cmg
    singular: configmapgenerator
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              content:
                type: string
